# Postgresql version 9.x
#   gem install pg
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= SETTINGS[:dev_database] %>
  pool: 5
  # username: <%= SETTINGS[:db_user] %>
  # password: <%= SETTINGS[:db_password] %>
  
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= SETTINGS[:test_database] %>
  pool: 16
  # username: <%= SETTINGS[:db_user] %>
  # password: <%= SETTINGS[:db_password] %>

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= SETTINGS[:production_database] %>
  pool: 16
  username: <%= SETTINGS[:db_user] %>
  password: <%= SETTINGS[:db_password] %>

